import { BrowserWindow } from 'electrobun';
import { CoreStore, createInitialCoreState } from '../../../../packages/core/src/index.js';
import { mapToViewModel } from '../../../../packages/view-model/src/index.js';

function escapeHtml(input: string): string {
	return input
		.replaceAll('&', '&amp;')
		.replaceAll('<', '&lt;')
		.replaceAll('>', '&gt;')
		.replaceAll('"', '&quot;')
		.replaceAll("'", '&#39;');
}

function renderHtml(summary: string, logLines: string[]): string {
	const items = logLines.map((line) => `<li>${escapeHtml(line)}</li>`).join('');
	return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Pixel Agents Desktop</title>
  <style>
    :root {
      color-scheme: light;
      --bg: #0f1220;
      --panel: rgba(24, 31, 52, 0.92);
      --text: #edf2ff;
      --muted: #a6b3d7;
      --accent: #46d2a8;
      --border: rgba(166, 179, 215, 0.24);
    }
    body {
      margin: 0;
      padding: 24px;
      font-family: ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      background: radial-gradient(circle at top, #1e2848 0%, var(--bg) 60%);
      color: var(--text);
    }
    main {
      max-width: 960px;
      margin: 0 auto;
      border: 1px solid var(--border);
      border-radius: 14px;
      padding: 20px;
      background: var(--panel);
      backdrop-filter: blur(8px);
    }
    h1 {
      margin: 0;
      font-size: 20px;
      font-weight: 600;
      letter-spacing: 0.06em;
    }
    p {
      margin: 8px 0 0;
      color: var(--muted);
      font-size: 13px;
    }
    .summary {
      margin-top: 16px;
      color: var(--accent);
      font-size: 14px;
      font-weight: 600;
    }
    ul {
      margin: 16px 0 0;
      padding-left: 18px;
      font-size: 13px;
      line-height: 1.5;
      color: var(--text);
    }
  </style>
</head>
<body>
  <main>
    <h1>Pixel Agents Desktop Prototype</h1>
    <p>Electrobun runtime window bootstrap is working. Core store events below are generated by the desktop host.</p>
    <div class="summary">${escapeHtml(summary)}</div>
    <ul>${items}</ul>
  </main>
</body>
</html>`;
}

function run(): void {
	const store = new CoreStore(createInitialCoreState());
	const logLines: string[] = [];

	const window = new BrowserWindow({
		title: 'Pixel Agents Desktop',
		frame: { x: 120, y: 80, width: 1100, height: 760 },
		html: '<html><body>Loading Pixel Agents Desktop...</body></html>',
		renderer: 'native',
		titleBarStyle: 'default',
		transparent: false,
	});

	const refresh = (reason: string) => {
		const vm = mapToViewModel(store.snapshot());
		const summary = `render:${reason} | tracked=${vm.toolbar.trackedAgentCount} | waiting=${vm.toolbar.waitingAgentCount}`;
		logLines.unshift(summary);
		if (logLines.length > 8) logLines.length = 8;
		window.webview.loadHTML(renderHtml(summary, logLines));
		console.log(`[desktop-electrobun][${summary}]`);
	};

	refresh('boot');

	const at = Date.now();
	store.dispatch({ type: 'agentAdded', id: 1, at });
	refresh('agentAdded#1');
	store.dispatch({ type: 'agentStatusSet', id: 1, status: 'active', at: at + 1 });
	refresh('agentStatus#1:active');
	store.dispatch({ type: 'agentAdded', id: 2, at: at + 2 });
	store.dispatch({ type: 'agentStatusSet', id: 2, status: 'waiting', at: at + 3 });
	refresh('agentStatus#2:waiting');
}

run();
